### ISSUE TITLE
Teleportation arc truncated in Fire scenario

### ISSUE THREAD

**Issue by AshishMBakshi** [usnistgov/HapticChallengeUE4#3]
**Observed Behavior**
The arc emerging from the motion controller during teleportation destination selection is truncated most of the time, showing just a short line at the source.

**Steps To Reproduce**
1. Run build of HapticChallengeUE4.
2. Select Fire scenario.
3. Press down on the top area of either motion controller's touchpad to begin teleportation.
4. Look at the arc emerging from the controller.

**Screenshots**
Most of the time, this is shown:

![vlcsnap-2019-06-06-00h13m10s551](https://user-images.githubusercontent.com/2073983/59006719-6ef61580-87f1-11e9-9bc0-2b45e70bf9c0.png)

Instead of the expected full arc:

![vlcsnap-2019-06-06-00h14m22s143](https://user-images.githubusercontent.com/2073983/59006730-8208e580-87f1-11e9-99ad-8d066d2dca70.png)

**Setup (please complete the following information):**
 - OS: Windows 10
 - Headset: Samsung Odyssey / HP WMR
 - Unreal Version 4.20.3
 - Computer Hardware: AMD Ryzen 7 1800X (8-core), 32 GB RAM, 1 TB NVMe SSD, Nvidia GeForce GTX 1080 Ti
 - Room Scale Setup: 5 x 5' space

**Comment by jrlvr** [comment]
This bug is actually due to a native bug within unreal. Essentially the navmesh occasionally disappears if it is trying to auto generate on top of instanced static meshes. Which is what the floor tiles are. There is a simple fix though. Just rebuild both geometry and paths under the build tab located above the viewport. This will regenerate the navmesh and allow the arcs navmesh trace to return true.
![RebuildPaths](https://user-images.githubusercontent.com/29755903/59120260-326e0b00-8912-11e9-9190-a0b03929b6f5.png)
