### ISSUE TITLE
Vive Pro Eye Performance Issues

### ISSUE THREAD

**Issue by ryanpoltermann** [usnistgov/HapticChallengeUE4#4]
**Observed Behavior**
Performance on Pro Eye is unusable.

**Steps To Reproduce**
1. Launch application and go to the Law Enforcement level.
No modifications were made to the configuration (straight from GitHub). Building application does not resolve the issue.

**Setup (please complete the following information):**
 - OS: Windows 10
 - Headset: Vive Pro Eye
 - Unreal Version: 4.20.3
 - Computer Hardware: Laptop, i7-8750H and RTX2070 MaxQ
 - Room Scale Setup: Approximately 10x10

**Additional context**
Build errors that were indicated as fixed still exist.  This may or may not be related to the issue.

**Comment by jrlvr** [comment]
Hey Ryan,

Sorry for the late reply. We have found a fix to the Vive Pro Eye frame rate issue. It is due to the level lighting not being built. When it is unbuilt the engine will default to dynamic lighting which will drastically reduce the frame rate. It took a while to narrow down this issue due to a bug in the engine in which it does not alert you that lighting needs to be rebuilt even though it does.

To rebuild, simply open the persistent level of each scenario which is labeled with _P and hit the Build button on the top toolbar. You will get a warning about the white box level (_WB) being hidden, ignore this and go ahead and continue with the lighting build anyway. Also, this may break the teleport mechanic in the fire level. If that happens simply click the drop-down arrow on the build icon in the toolbar and rebuild geometry and paths after building the lighting, that will fix it.
